CREATE TABLE person
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(255),
    email VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE request
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(255),
    requestor_id BIGINT,
    created     TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (requestor_id) REFERENCES person (id)
);

CREATE TABLE item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255),
    description VARCHAR(255),
    available   BOOLEAN,
    owner_id   BIGINT,
    request_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (owner_id) REFERENCES person (id),
    FOREIGN KEY (request_id) REFERENCES request (id)
);

CREATE TABLE booking
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    time_start TIMESTAMP,
    time_end   TIMESTAMP,
    item_id   BIGINT,
    booker_id BIGINT,
    status     VARCHAR(255),
    PRIMARY KEY (id),
    FOREIGN KEY (item_id) REFERENCES item (id),
    FOREIGN KEY (booker_id) REFERENCES person (id)
);
